### PR TITLE
Add routes for experiment page tabs

### PR DESCRIPTION
**Pull request by gorarakelyan**

### CODE REVIEW

**Comment by gorarakelyan** [comment]
Resolves aimhubio/aim#421

**Comment by gorarakelyan** [comment]
A bit of workaround unless we move tabs to separate components and load their content on demand.

**Comment by roubkar** [comment]
@gorarakelyan wouldn't it be simpler to have a single route and keep active tab state as URL query param?
e.g. `?tab=metrics`

**Comment by gorarakelyan** [comment]
I think `:experiment/:run/:tab` is simpler than `experiment/run?tab=:tab`, isn't it? 

re `single route`: Initially I implemented in the way you mentioned, but then refactored to not bother with handling unknown tabs and redirecting to notfoundscreen manually. I would have used `:experiment/:run/:tag<oneOf(metrics, params, system, ..)>` if react router provided that ability.

**Comment by roubkar** [comment]
You can provide array of strings to `path` prop of `Route` component
```javascript
...
path={[
   screens.HUB_PROJECT_EXPERIMENT_PARAMS_TAB,
   screens.HUB_PROJECT_EXPERIMENT_METRICS_TAB,
   ...
]}
...

**Review by roubkar — APPROVED** [review]
lgtm

**Pull request merged**
