### PR TITLE
Add ability to hide columns which values are all the same

### PR DESCRIPTION
**Pull request by roubkar**

### CODE REVIEW

**Comment by gorarakelyan** [comment]
Any thoughts on how to name this button? @roubkar @SGevorg 

Screen Shot 2021-03-15 at 17 25 33

**Comment by roubkar** [comment]
How about leaving it this way and add a tooltip with detailed description?

**Comment by roubkar** [comment]
@gorarakelyan what do you think of this?

Screen Shot 2021-03-15 at 22 18 11

**Comment by gorarakelyan** [comment]
Looks good to me 👍

**Pull request merged**
