### PR TITLE
Add std dev and std err aggregation modes

### PR DESCRIPTION
**Pull request by roubkar**
- Add standard deviation aggregation mode
- Add standard error aggregation mode
- Change context box table group value layout

### CODE REVIEW

**Comment by roubkar** [comment]
Resolves https://github.com/aimhubio/aim/issues/381

**Comment by gorarakelyan** [comment]
Probably we should think of calculating only those aggregation methods which are selected by user

**Comment by gorarakelyan** [comment]
We added 4 additional methods, so the compute time will be increased by x4, right?

**Comment by roubkar** [comment]
I was thinking of adding lazy aggregation calculation with improving overall our aggregation calculation performance within separate PR

**Comment by gorarakelyan** [comment]
Yea, totally agree.

**Comment by gorarakelyan** [comment]
thoughts?
image

**Comment by gorarakelyan** [comment]
also made popup a bit clearer

image

**Review by gorarakelyan — APPROVED** [review]

**Pull request merged**
