### PR TITLE
Add ability to toggle metric visibility in explore panel

### PR DESCRIPTION
**Pull request by roubkar**

### CODE REVIEW

**Comment by roubkar** [comment]
@gorarakelyan please check and provide some feedback regarding the UI of row visualization popover

Screen Shot 2021-03-16 at 00 00 54

**Comment by gorarakelyan** [comment]
@roubkar Made popover a bit simpler

image

image

thoughts?

**Comment by gorarakelyan** [comment]
seems there is an issue with parplot

image

I have only 9 runs, not 11. Plus if I select only parameters, runs visualization toggler does not work

**Comment by roubkar** [comment]
Will check now

**Comment by roubkar** [comment]
@gorarakelyan can you please check again whether issue with hiding rows in parplot view is fixed?

**Comment by gorarakelyan** [comment]
will do it now

**Comment by gorarakelyan** [comment]
hide/show works fine now, but the counter displays incorrect number of hidden rows

**Comment by roubkar** [comment]
I noticed that the issue with count happens when you select hide all option.
Should be fixed now

**Comment by gorarakelyan** [comment]
will check now

**Comment by gorarakelyan** [comment]
resolved, but i noticed parplot brushes are broken

**Comment by roubkar** [comment]
noticed it too, will open an issue for that

**Comment by gorarakelyan** [comment]
okay, the rest looks good to me

**Review by gorarakelyan — APPROVED** [review]

**Pull request merged**
