### PR TITLE
Display popover with run information when selecting ParPlot point

### PR DESCRIPTION
**Pull request by roubkar**

### CODE REVIEW

**Comment by roubkar** [comment]
Resolves https://github.com/aimhubio/aim/issues/411

**Comment by gorarakelyan** [comment]
@roubkar there is a problem when trying to select a run which doesnt have all the axes values.

e.g. I have 3 vertical axes - A, B, C and 3 runs - 1, 2, 3, where:
run1 -> A=1, B=3, C=1
run2 -> A=2, B=1, C=2
run3 -> A=3, B=None, C=3

```
A      B      C
|      |      |
1 ---- 2 ---- 1
2 ---- - ---- 2
3 ---- 1 ---- 3
```

When I try to select run3 from the context table, the popover doesn't open

**Comment by gorarakelyan** [comment]
And when there are 2 runs that have missing points, the popover body is not updated, except for the tag information.

**Comment by gorarakelyan** [comment]
If it helps, I was experimenting with one parameter and 2 metrics as vertical axes. The missing/untracked values belonged to metric type axis.

**Comment by roubkar** [comment]
@gorarakelyan thanks for providing detailed feedback.
All the issues mentioned above should be resolved.

**Comment by gorarakelyan** [comment]
Will check it out now

**Comment by gorarakelyan** [comment]
Works great

**Pull request merged**
