### PR TITLE
Optimize group aggregation performance

### PR DESCRIPTION
**Pull request by roubkar**
- Keep `aggregated` flag with chart settings properties in state
- Update only panel charts when `aggregated` flag is toggled
- Use lazy aggregation depending on aggregation modes

### CODE REVIEW

**Comment by roubkar** [comment]
Resolves https://github.com/aimhubio/aim/issues/407

**Comment by gorarakelyan** [comment]
smth breaks down when `median` aggregation mode is selected

image

**Comment by roubkar** [comment]
should be fixed now

**Comment by gorarakelyan** [comment]
will check now

**Pull request merged**
